### ISSUE TITLE
Add Project Description and Live Demo Link to README

### ISSUE THREAD

**Issue by jsug9** [AKeeganDev/recipe_app#45]
Hi @AKeeganDev and @emyrue!

First of all, congratulations on the fantastic progress you've made on the project! It's been great to see the development so far. However, I noticed that the project's README file lacks a clear description, which makes it challenging for newcomers to understand the project's purpose and goals. I recommend adding a comprehensive description to the README to better communicate your project's objectives.

Additionally, @hsztan expressed interest in checking out the app's progress but couldn't find a link to the live demo. It would be beneficial to include a link to the live demo within the project description so that users can easily access and explore the app.

Implementing these suggestions will help improve the project's accessibility and user experience.

Keep up the excellent work! 🤘

**Comment by AKeeganDev** [comment]
You are clever on indeed @jsug9! I'm happy to inform you that the app is up and running and a detailed README has been added!

Feel free to check out the readme for the demo link. Maybe you can research Tongo's favorite recipe and post it as a sample for my site!

Cheers my friend

**Comment by jsug9** [comment]
Hi @AKeeganDev! I was delighted to read the project description and try out the live demo. I had fun adding my recipe and enjoyed how easy it was to set up my profile. Though, I noticed the web performed slowly, which might be due to N + 1 problems. I recommend improving the performance to further enhance the UX.
I am looking forward to see the recipes of @hsztan 🙌

**Comment by AKeeganDev** [comment]
@jsug9 , turns out it was the minimagick gem we were using for image sizing that was slowing down the app. @emyrue figured that out. It runs a lot smoother now! Also, Render is very slow when you use their free tier. They even advertise faster speeds for paying for the service. It shuts down the site until someone accesses it. Then once it "wakes up" it works smoothly. I think it is a Render problem.

**Comment by jsug9** [comment]
Great!!! Looking forward to trying it out again
